version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2015

configuration:
- Debug
- Release

build:
    project: SpheremapTool.sln
    parallel: false
    verbosity: minimal
    
artifacts:
   path: Release\SpheremapTool.exe
   name: SpheremapToolRelease.exe
