version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2019

configuration:
- Debug
- Release

platform:
- x86

build:
    project: SpheremapTool.sln
    parallel: true
    verbosity: minimal
